version: 2

registries:
  ghcr: # Define access for a private registry
    type: docker-registry
    url: ghcr.io
    username: PAT
    password: ${{secrets.BASE_CONTAINER_IMAGE_READER_DEPENDABOT}}

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    groups:
      minor-patches:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    ignore:
      # Because this is so dependent on the remote server we use
      - dependency-name: '@elastic/elasticsearch'
      # Because whatever we have needs to match what @primer/react also uses
      - dependency-name: 'styled-components'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
    groups:
      minor-patches:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'github/internal-actions'

  - package-ecosystem: 'docker'
    registries:
      - ghcr
    directory: '/'
    schedule:
      interval: daily
    groups:
      baseImages:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'node' # Ignore Dockerfile.openapi_decorator
