# Pre-commit configuration for comprehensive linting and security checks
# Install with: pip install pre-commit && pre-commit install
repos:
  # General file quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: detect-private-key

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  # Docker file linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # Python linting (for any Python scripts)
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503']

  # JavaScript/TypeScript linting
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false

      - id: prettier
        name: Prettier
        entry: npm run prettier
        language: system
        files: \.(js|jsx|ts|tsx|json|yaml|yml|md)$
        pass_filenames: false

      - id: typescript
        name: TypeScript Check
        entry: npm run tsc
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Trivy for security scanning
  - repo: local
    hooks:
      - id: trivy-fs
        name: Trivy filesystem scan
        entry: trivy fs --format table --exit-code 1 --severity HIGH,CRITICAL .
        language: system
        pass_filenames: false
