name: Commit Signing Gate

# **What it does**: Verifies all commits in a PR are properly signed
# **Why we have it**: Ensure commit integrity and prevent tampered commits
# **Who does it impact**: All contributors, security team

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  verify-commit-signatures:
    name: Verify Commit Signatures
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Verify commit signatures
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Commit Signature Verification" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Get all commits in the PR
          commits=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits)

          unsigned_commits=()
          total_commits=$(echo "$commits" | jq length)

          echo "**Total commits in PR**: $total_commits" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Check each commit's verification status
          for i in $(seq 0 $((total_commits - 1))); do
            sha=$(echo "$commits" | jq -r ".[$i].sha")
            verified=$(echo "$commits" | jq -r ".[$i].commit.verification.verified")
            reason=$(echo "$commits" | jq -r ".[$i].commit.verification.reason")
            
            if [[ "$verified" != "true" ]]; then
              unsigned_commits+=("$sha")
              echo "❌ **$sha**: Not verified ($reason)" >> $GITHUB_STEP_SUMMARY
            else
              echo "✅ **$sha**: Verified" >> $GITHUB_STEP_SUMMARY  
            fi
          done

          if [[ ${#unsigned_commits[@]} -gt 0 ]]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**❌ Unsigned commits found:** ${#unsigned_commits[@]}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "All commits must be signed. Please sign your commits and force-push:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "git rebase --exec 'git commit --amend --no-edit -n -S' @{u}" >> $GITHUB_STEP_SUMMARY
            echo "git push --force-with-lease" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "✅ **All commits properly signed**" >> $GITHUB_STEP_SUMMARY
          fi
