name: 'Copilot Environment Setup'

# **What it does**: Sets up the environment for Copilot coding agent to test content and script changes.
# **Why we have it**: Ensures Copilot can validate content with linters and formatters before making changes.
# **Who does it impact**: Copilot coding agent and developers using repository custom instructions.

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  copilot-setup-steps:
    if: github.repository == 'github/docs-internal'
    runs-on: ${{ github.repository == 'github/docs-internal' && 'ubuntu-latest' }}

    steps:
      - name: Check out repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

   #   - name: Set up Node and dependencies
   #     uses: ./.github/actions/node-npm-setup

   # Running `node-npm-setup` in full to cache dependencies does not seem to work.
   # Runing the remaining two steps manually for now which should be quicker.

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: 'package.json'
          cache: npm

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Environment setup summary
        run: |
          echo "✅ Copilot environment setup completed successfully!"
          echo ""
          echo "Available commands for content validation:"
          echo "- Content linting: npm run lint-content -- --paths <file-paths>"
          echo "- Prettier formatting: npm run prettier-check -- <file-paths>"
          echo "- ESLint: npm run lint"
          echo "- TypeScript check: npm run tsc"
          echo "- All tests: npm test"
          echo ""
          echo "For more guidance, see .github/copilot-instructions.md"
