---
name: Dependency Review

# **What it does**: Reviews dependencies for vulnerabilities and license compliance.
# **Why we have it**: Security scanning and compliance.
# **Who does it impact**: Docs engineering, security.

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  dependency-review:
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Dependency Review
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
        with:
          config-file: './.github/dependency-review-config.yml'
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, GPL-3.0
          retry-on-snapshot-warnings: true

      - uses: ./.github/actions/slack-alert
        if: ${{ failure() && github.event_name != 'workflow_dispatch' }}
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
