name: Secrets Scanning

# **What it does**: Scans for secrets and sensitive information in the repository
# **Why we have it**: Prevent accidental secret commits and security leaks
# **Who does it impact**: Security team, all contributors

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write
  actions: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository == 'github/docs-internal' || github.repository == 'github/docs'
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Full history for comprehensive scan

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@cb7149a9c1a27f5a80cb6b2c0c4f4eaa0e34443f # v2.3.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Optional license key
        with:
          config-path: .gitleaks.toml
          redact: true
          fail: true

      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: gitleaks-report-${{ github.run_id }}
          path: results.sarif
          retention-days: 30

      - name: Report scan results
        if: always()
        run: |
          echo "## Secrets Scanning Results" >> $GITHUB_STEP_SUMMARY
          if [[ -f "results.sarif" ]]; then
            findings=$(jq -r '.runs[0].results | length' results.sarif 2>/dev/null || echo "0")
            if [[ "$findings" == "0" ]]; then
              echo "✅ No secrets detected in repository scan" >> $GITHUB_STEP_SUMMARY
            else
              echo "❌ $findings potential secrets found - check the uploaded report" >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "✅ Secrets scan completed successfully" >> $GITHUB_STEP_SUMMARY
          fi
          
      - name: Check out repo
        if: ${{ failure() }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - uses: ./.github/actions/slack-alert
        if: ${{ failure() }}
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
